export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';
export const SET_AUTH_REDIRECT='SET_AUTH_REDIRECT';

export const USER_LIST_START='USER_LIST_START';
export const USER_LIST_SUCCESS='USER_LIST_SUCCESS';
export const USER_LIST_FAIL='USER_LIST_FAIL';
export const SET_RECEIVER='SET_RECEIVER';

export const MESSAGE_SEND_START='MESSAGE_SEND_START';
export const MESSAGE_SEND_SUCCESS='MESSAGE_SEND_SUCCESS';
export const MESSAGE_SEND_FAIL='MESSAGE_SEND_FAIL';

export const MESSAGE_FETCH_START='MESSAGE_FETCH_START';
export const MESSAGE_FETCH_SUCCESS='MESSAGE_FETCH_SUCCESS';
export const MESSAGE_FETCH_FAIL='MESSAGE_FETCH_FAIL';

